# Generated by Django 5.1.3 on 2024-11-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('owner_occupied', models.BooleanField(default=False)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('mailing_city', models.CharField(max_length=100)),
                ('mailing_state', models.CharField(max_length=50)),
                ('mailing_zip', models.CharField(max_length=15)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('last_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assessed_land_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loans_details', models.JSONField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.DateTimeField()),
                ('est_resale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opening_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rental_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('link', models.URLField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trustee_sale_number', models.CharField(blank=True, max_length=255, null=True)),
                ('apn', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
