# Generated by Django 5.1.3 on 2024-11-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='legal',
            field=models.ForeignKey(blank=True, help_text='Reference to any legal proceedings associated with the auction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.legalproceeding'),
        ),
    ]
