# Generated by Django 5.1.3 on 2024-12-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dublicatecheck_remove_auction_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dublicatecheck',
            old_name='auction',
            new_name='is_auction',
        ),
    ]
