# Generated by Django 5.1.3 on 2024-11-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auction_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='owner',
        ),
    ]
