# Generated by Django 5.1.3 on 2024-12-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_auction_dublicatecheck_is_auction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DublicateCheck',
            new_name='DuplicateCheck',
        ),
    ]
