# Generated by Django 5.1.3 on 2024-12-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_dublicatecheck_duplicatecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duplicatecheck',
            old_name='reformated_address',
            new_name='reformatted_address',
        ),
    ]
