# Generated by Django 5.1.3 on 2024-11-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_owner_property_ownership_owner_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinformation',
            name='property',
        ),
        migrations.AddField(
            model_name='salesinformation',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auction'),
        ),
    ]
