# Generated by Django 5.1.3 on 2024-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_duplicatecheck_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecheck',
            name='reformatted_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
