# Generated by Django 5.1.3 on 2024-11-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_auction_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalproceeding',
            name='property',
            field=models.ForeignKey(help_text='The property involved in the legal proceeding', on_delete=django.db.models.deletion.CASCADE, related_name='legal_proceedings', to='api.property'),
        ),
    ]
