# Generated by Django 5.1.3 on 2024-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_duplicatecheck_reformatted_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecheck',
            name='source_name',
            field=models.CharField(choices=[('Auction.com', 'auction.com'), ('Foreclosure.com', 'foreclosure.com'), ('Salesweb', 'salesweb'), ('Realtybid', 'realtybid'), ('Njcourt', 'njcourt'), ('Bids', 'bids'), ('FL', 'fl'), ('Xome', 'xome'), ('ASAP', 'asap')], max_length=20),
        ),
    ]
