# Generated by Django 5.1.3 on 2024-11-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ownership_owner_alter_ownership_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageanddebt',
            name='property',
            field=models.ForeignKey(help_text='The property associated with this mortgage or debt', on_delete=django.db.models.deletion.CASCADE, related_name='mortgages_and_debts', to='api.property'),
        ),
        migrations.AlterField(
            model_name='taxlien',
            name='property',
            field=models.ForeignKey(help_text='The property on which the tax lien is placed', on_delete=django.db.models.deletion.CASCADE, related_name='tax_liens', to='api.property'),
        ),
    ]
